version: '3'

services:

  mongo:
    image: mongo
    networks:
      - rsblog-nw
    volumes:
      - db-data:/data/db

  rsblog:
    image: rsblog
    ports:
      - 80:8888
    networks:
      - rsblog-nw
    environment:
      RSBLOG_PORT: 8888
      RSBLOG_MONGO_URI: mongodb://mongo/rsblog
      RSBLOG_ADMIN_LOGIN: admin
      RSBLOG_ADMIN_PASSW: admin

networks:
  rsblog-nw:
    driver: bridge

volumes:
  db-data: